//Benicio.Braga60@yahoo.com

###
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Python"
}

###
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Benicio.Braga60@yahoo.com",
  "password": "123456"
}

###
GET http://localhost:3333/courses


### 
GET http://localhost:3333/courses/bc2f9f24-e0e4-4500-8b3a-778e2ab6fcc0